create table if not exists public.canvas_announcements (
  id bigint generated by default as identity primary key,

  course_id bigint not null,
  course_name text not null,

  announcement_id bigint not null,
  title text not null,
  message_html text,

  posted_at timestamptz,
  delayed_post_at timestamptz,
  published boolean,

  html_url text,

  attachments_json jsonb not null default '[]'::jsonb,
  content_fingerprint text not null,

  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_changed_at timestamptz not null default now(),

  unique (course_id, announcement_id)
);

create index if not exists idx_canvas_announcements_course_id
  on public.canvas_announcements (course_id);


create table if not exists public.learningx_weeks (
  id bigint generated by default as identity primary key,

  course_id bigint not null,
  course_name text not null,

  week_position integer not null,

  unlock_at timestamptz,
  lock_at timestamptz,
  due_at timestamptz,
  late_at timestamptz,

  is_unlocked boolean not null default false,
  unlock_notified_at timestamptz,

  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),

  unique (course_id, week_position)
);

create index if not exists idx_learningx_weeks_course_id
  on public.learningx_weeks (course_id);


create table if not exists public.notification_log (
  id bigint generated by default as identity primary key,

  event_type text not null,
  course_id bigint,
  source_id text,

  channel text not null default 'ntfy',

  title text,
  message text,

  status text not null,
  error_message text,

  sent_at timestamptz not null default now()
);

create index if not exists idx_notification_log_course_id
  on public.notification_log (course_id);

create index if not exists idx_notification_log_sent_at
  on public.notification_log (sent_at desc);


alter table public.canvas_announcements enable row level security;
alter table public.learningx_weeks enable row level security;
alter table public.notification_log enable row level security;


grant select, insert, update, delete
on table public.canvas_announcements
to service_role;

grant select, insert, update, delete
on table public.learningx_weeks
to service_role;

grant select, insert, update, delete
on table public.notification_log
to service_role;

grant usage, select
on all sequences in schema public
to service_role;