create table if not exists public.canvas_conversations (
  id bigint generated by default as identity primary key,

  conversation_id text not null unique,
  course_id bigint,
  course_name text not null,

  subject text not null,
  last_message text,
  last_message_at timestamptz,
  click_url text,

  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create index if not exists idx_canvas_conversations_course_id
  on public.canvas_conversations (course_id);

alter table public.canvas_conversations enable row level security;

grant select, insert, update, delete
on table public.canvas_conversations
to service_role;

grant usage, select
on all sequences in schema public
to service_role;
