create table if not exists public.canvas_items (
  id bigint generated by default as identity primary key,

  course_id bigint not null,
  course_name text not null,

  module_id bigint not null,
  module_name text not null,

  item_id bigint not null,
  item_type text not null,
  title text not null,

  html_url text,
  external_url text,

  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),

  unique (course_id, item_id)
);

create index if not exists idx_canvas_items_course_id
  on public.canvas_items (course_id);

create index if not exists idx_canvas_items_module_id
  on public.canvas_items (module_id);


create table if not exists public.watcher_runs (
  id bigint generated by default as identity primary key,

  started_at timestamptz not null default now(),
  finished_at timestamptz,

  status text not null default 'running',

  courses_checked integer not null default 0,
  items_seen integer not null default 0,
  new_items integer not null default 0,

  error_message text
);